// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvCdKMGrS-hGv3jLvg2mbLrF-KXxBMJKM',
    appId: '1:551557072407:web:f60aed5980a1ba69affe52',
    messagingSenderId: '551557072407',
    projectId: 'prm393-mobileshop',
    authDomain: 'prm393-mobileshop.firebaseapp.com',
    storageBucket: 'prm393-mobileshop.firebasestorage.app',
    measurementId: 'G-1L7YB792PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvCdKMGrS-hGv3jLvg2mbLrF-KXxBMJKM',
    appId: '1:551557072407:android:8dab3e884951d9d7affe52',
    messagingSenderId: '551557072407',
    projectId: 'prm393-mobileshop',
    storageBucket: 'prm393-mobileshop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdpVrcV4bhKHwnbcJlXFZsFKtX9Yy2t1Q',
    appId: '1:551557072407:ios:ed842614bbf04918affe52',
    messagingSenderId: '551557072407',
    projectId: 'prm393-mobileshop',
    storageBucket: 'prm393-mobileshop.firebasestorage.app',
    iosBundleId: 'com.example.projectMobileshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdpVrcV4bhKHwnbcJlXFZsFKtX9Yy2t1Q',
    appId: '1:551557072407:ios:ed842614bbf04918affe52',
    messagingSenderId: '551557072407',
    projectId: 'prm393-mobileshop',
    storageBucket: 'prm393-mobileshop.firebasestorage.app',
    iosBundleId: 'com.example.projectMobileshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvCdKMGrS-hGv3jLvg2mbLrF-KXxBMJKM',
    appId: '1:551557072407:web:b1a51b3ab9a26089affe52',
    messagingSenderId: '551557072407',
    projectId: 'prm393-mobileshop',
    authDomain: 'prm393-mobileshop.firebaseapp.com',
    storageBucket: 'prm393-mobileshop.firebasestorage.app',
    measurementId: 'G-G4DP53GF3L',
  );

}